Repository quay/clair, pull requests merged in 2019-10, with the labels that each got.

#859 dockerfile: bump to Go 1.13
  Dockerfile
Labels: area/distribution, kind/bug, lifecycle/preserve, low hanging fruit, priority/urgent

#860 dockerfile: bump Go to 1.13
  Dockerfile
Labels: area/distribution, lifecycle/preserve, low hanging fruit

#856 Fix broken links in CONTRIBUTING file
  .github/CONTRIBUTING.md
Labels: kind/documentation, kind/regression
